/*
=============================================================================
 Copyright   : (c) 2008 semantics GmbH. All Rights Reserved.
 Rep./File   : $URL$
 Date        : $Date$
 Author      : Christian Heimes
 License     : FreeImage Public License (FIPL)
               GNU General Public License (GPL)
 Worker      : $Author$
 Revision    : $Rev$
 Purpose     : Simpe C module to expose FI constants and enums
=============================================================================

 COVERED CODE IS PROVIDED UNDER THIS LICENSE ON AN "AS IS" BASIS, WITHOUT
 WARRANTY OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING, WITHOUT
 LIMITATION, WARRANTIES THAT THE COVERED CODE IS FREE OF DEFECTS, MERCHANTABLE,
 FIT FOR A PARTICULAR PURPOSE OR NON-INFRINGING. THE ENTIRE RISK AS TO THE
 QUALITY AND PERFORMANCE OF THE COVERED CODE IS WITH YOU. SHOULD ANY COVERED
 CODE PROVE DEFECTIVE IN ANY RESPECT, YOU (NOT THE INITIAL DEVELOPER OR ANY
 OTHER CONTRIBUTOR) ASSUME THE COST OF ANY NECESSARY SERVICING, REPAIR OR
 CORRECTION. THIS DISCLAIMER OF WARRANTY CONSTITUTES AN ESSENTIAL PART OF
 THIS LICENSE. NO USE OF ANY COVERED CODE IS AUTHORIZED HEREUNDER EXCEPT UNDER
 THIS DISCLAIMER.
*/

#include "Python.h"
#include "smc_fi.h"
#include "lcms2.h"

static PyMethodDef lcmsconstants_methods[] = {
    {NULL, NULL}    /* sentinel */
};

PyDoc_STRVAR(module_doc,
"LCMS constants.\n\
\n\
This module exposes all LCMS integer constants.");

PyMODINIT_FUNC
initlcmsconstants(void)
{
    PyObject *m;
    m = Py_InitModule3("lcmsconstants", lcmsconstants_methods, module_doc);
    if (m == NULL)
        return;

    /* MARKER, the rest of the file is autogenerated! */
    PyModule_AddIntConstant(m, "TYPE_GRAY_8", TYPE_GRAY_8);
    PyModule_AddIntConstant(m, "TYPE_GRAY_8_REV", TYPE_GRAY_8_REV);
    PyModule_AddIntConstant(m, "TYPE_GRAY_16", TYPE_GRAY_16);
    PyModule_AddIntConstant(m, "TYPE_GRAY_16_REV", TYPE_GRAY_16_REV);
    PyModule_AddIntConstant(m, "TYPE_GRAY_16_SE", TYPE_GRAY_16_SE);
    PyModule_AddIntConstant(m, "TYPE_GRAYA_8", TYPE_GRAYA_8);
    PyModule_AddIntConstant(m, "TYPE_GRAYA_16", TYPE_GRAYA_16);
    PyModule_AddIntConstant(m, "TYPE_GRAYA_16_SE", TYPE_GRAYA_16_SE);
    PyModule_AddIntConstant(m, "TYPE_GRAYA_8_PLANAR", TYPE_GRAYA_8_PLANAR);
    PyModule_AddIntConstant(m, "TYPE_GRAYA_16_PLANAR", TYPE_GRAYA_16_PLANAR);
    PyModule_AddIntConstant(m, "TYPE_RGB_8", TYPE_RGB_8);
    PyModule_AddIntConstant(m, "TYPE_RGB_8_PLANAR", TYPE_RGB_8_PLANAR);
    PyModule_AddIntConstant(m, "TYPE_BGR_8", TYPE_BGR_8);
    PyModule_AddIntConstant(m, "TYPE_BGR_8_PLANAR", TYPE_BGR_8_PLANAR);
    PyModule_AddIntConstant(m, "TYPE_RGB_16", TYPE_RGB_16);
    PyModule_AddIntConstant(m, "TYPE_RGB_16_PLANAR", TYPE_RGB_16_PLANAR);
    PyModule_AddIntConstant(m, "TYPE_RGB_16_SE", TYPE_RGB_16_SE);
    PyModule_AddIntConstant(m, "TYPE_BGR_16", TYPE_BGR_16);
    PyModule_AddIntConstant(m, "TYPE_BGR_16_PLANAR", TYPE_BGR_16_PLANAR);
    PyModule_AddIntConstant(m, "TYPE_BGR_16_SE", TYPE_BGR_16_SE);
    PyModule_AddIntConstant(m, "TYPE_RGBA_8", TYPE_RGBA_8);
    PyModule_AddIntConstant(m, "TYPE_RGBA_8_PLANAR", TYPE_RGBA_8_PLANAR);
    PyModule_AddIntConstant(m, "TYPE_RGBA_16", TYPE_RGBA_16);
    PyModule_AddIntConstant(m, "TYPE_RGBA_16_PLANAR", TYPE_RGBA_16_PLANAR);
    PyModule_AddIntConstant(m, "TYPE_RGBA_16_SE", TYPE_RGBA_16_SE);
    PyModule_AddIntConstant(m, "TYPE_ARGB_8", TYPE_ARGB_8);
    PyModule_AddIntConstant(m, "TYPE_ARGB_16", TYPE_ARGB_16);
    PyModule_AddIntConstant(m, "TYPE_ABGR_8", TYPE_ABGR_8);
    PyModule_AddIntConstant(m, "TYPE_ABGR_16", TYPE_ABGR_16);
    PyModule_AddIntConstant(m, "TYPE_ABGR_16_PLANAR", TYPE_ABGR_16_PLANAR);
    PyModule_AddIntConstant(m, "TYPE_ABGR_16_SE", TYPE_ABGR_16_SE);
    PyModule_AddIntConstant(m, "TYPE_BGRA_8", TYPE_BGRA_8);
    PyModule_AddIntConstant(m, "TYPE_BGRA_16", TYPE_BGRA_16);
    PyModule_AddIntConstant(m, "TYPE_BGRA_16_SE", TYPE_BGRA_16_SE);
    PyModule_AddIntConstant(m, "TYPE_CMY_8", TYPE_CMY_8);
    PyModule_AddIntConstant(m, "TYPE_CMY_8_PLANAR", TYPE_CMY_8_PLANAR);
    PyModule_AddIntConstant(m, "TYPE_CMY_16", TYPE_CMY_16);
    PyModule_AddIntConstant(m, "TYPE_CMY_16_PLANAR", TYPE_CMY_16_PLANAR);
    PyModule_AddIntConstant(m, "TYPE_CMY_16_SE", TYPE_CMY_16_SE);
    PyModule_AddIntConstant(m, "TYPE_CMYK_8", TYPE_CMYK_8);
    PyModule_AddIntConstant(m, "TYPE_CMYKA_8", TYPE_CMYKA_8);
    PyModule_AddIntConstant(m, "TYPE_CMYK_8_REV", TYPE_CMYK_8_REV);
    PyModule_AddIntConstant(m, "TYPE_YUVK_8", TYPE_YUVK_8);
    PyModule_AddIntConstant(m, "TYPE_CMYK_8_PLANAR", TYPE_CMYK_8_PLANAR);
    PyModule_AddIntConstant(m, "TYPE_CMYK_16", TYPE_CMYK_16);
    PyModule_AddIntConstant(m, "TYPE_CMYK_16_REV", TYPE_CMYK_16_REV);
    PyModule_AddIntConstant(m, "TYPE_YUVK_16", TYPE_YUVK_16);
    PyModule_AddIntConstant(m, "TYPE_CMYK_16_PLANAR", TYPE_CMYK_16_PLANAR);
    PyModule_AddIntConstant(m, "TYPE_CMYK_16_SE", TYPE_CMYK_16_SE);
    PyModule_AddIntConstant(m, "TYPE_KYMC_8", TYPE_KYMC_8);
    PyModule_AddIntConstant(m, "TYPE_KYMC_16", TYPE_KYMC_16);
    PyModule_AddIntConstant(m, "TYPE_KYMC_16_SE", TYPE_KYMC_16_SE);
    PyModule_AddIntConstant(m, "TYPE_KCMY_8", TYPE_KCMY_8);
    PyModule_AddIntConstant(m, "TYPE_KCMY_8_REV", TYPE_KCMY_8_REV);
    PyModule_AddIntConstant(m, "TYPE_KCMY_16", TYPE_KCMY_16);
    PyModule_AddIntConstant(m, "TYPE_KCMY_16_REV", TYPE_KCMY_16_REV);
    PyModule_AddIntConstant(m, "TYPE_KCMY_16_SE", TYPE_KCMY_16_SE);
    PyModule_AddIntConstant(m, "TYPE_CMYK5_8", TYPE_CMYK5_8);
    PyModule_AddIntConstant(m, "TYPE_CMYK5_16", TYPE_CMYK5_16);
    PyModule_AddIntConstant(m, "TYPE_CMYK5_16_SE", TYPE_CMYK5_16_SE);
    PyModule_AddIntConstant(m, "TYPE_KYMC5_8", TYPE_KYMC5_8);
    PyModule_AddIntConstant(m, "TYPE_KYMC5_16", TYPE_KYMC5_16);
    PyModule_AddIntConstant(m, "TYPE_KYMC5_16_SE", TYPE_KYMC5_16_SE);
    PyModule_AddIntConstant(m, "TYPE_CMYK6_8", TYPE_CMYK6_8);
    PyModule_AddIntConstant(m, "TYPE_CMYK6_8_PLANAR", TYPE_CMYK6_8_PLANAR);
    PyModule_AddIntConstant(m, "TYPE_CMYK6_16", TYPE_CMYK6_16);
    PyModule_AddIntConstant(m, "TYPE_CMYK6_16_PLANAR", TYPE_CMYK6_16_PLANAR);
    PyModule_AddIntConstant(m, "TYPE_CMYK6_16_SE", TYPE_CMYK6_16_SE);
    PyModule_AddIntConstant(m, "TYPE_CMYK7_8", TYPE_CMYK7_8);
    PyModule_AddIntConstant(m, "TYPE_CMYK7_16", TYPE_CMYK7_16);
    PyModule_AddIntConstant(m, "TYPE_CMYK7_16_SE", TYPE_CMYK7_16_SE);
    PyModule_AddIntConstant(m, "TYPE_KYMC7_8", TYPE_KYMC7_8);
    PyModule_AddIntConstant(m, "TYPE_KYMC7_16", TYPE_KYMC7_16);
    PyModule_AddIntConstant(m, "TYPE_KYMC7_16_SE", TYPE_KYMC7_16_SE);
    PyModule_AddIntConstant(m, "TYPE_CMYK8_8", TYPE_CMYK8_8);
    PyModule_AddIntConstant(m, "TYPE_CMYK8_16", TYPE_CMYK8_16);
    PyModule_AddIntConstant(m, "TYPE_CMYK8_16_SE", TYPE_CMYK8_16_SE);
    PyModule_AddIntConstant(m, "TYPE_KYMC8_8", TYPE_KYMC8_8);
    PyModule_AddIntConstant(m, "TYPE_KYMC8_16", TYPE_KYMC8_16);
    PyModule_AddIntConstant(m, "TYPE_KYMC8_16_SE", TYPE_KYMC8_16_SE);
    PyModule_AddIntConstant(m, "TYPE_CMYK9_8", TYPE_CMYK9_8);
    PyModule_AddIntConstant(m, "TYPE_CMYK9_16", TYPE_CMYK9_16);
    PyModule_AddIntConstant(m, "TYPE_CMYK9_16_SE", TYPE_CMYK9_16_SE);
    PyModule_AddIntConstant(m, "TYPE_KYMC9_8", TYPE_KYMC9_8);
    PyModule_AddIntConstant(m, "TYPE_KYMC9_16", TYPE_KYMC9_16);
    PyModule_AddIntConstant(m, "TYPE_KYMC9_16_SE", TYPE_KYMC9_16_SE);
    PyModule_AddIntConstant(m, "TYPE_CMYK10_8", TYPE_CMYK10_8);
    PyModule_AddIntConstant(m, "TYPE_CMYK10_16", TYPE_CMYK10_16);
    PyModule_AddIntConstant(m, "TYPE_CMYK10_16_SE", TYPE_CMYK10_16_SE);
    PyModule_AddIntConstant(m, "TYPE_KYMC10_8", TYPE_KYMC10_8);
    PyModule_AddIntConstant(m, "TYPE_KYMC10_16", TYPE_KYMC10_16);
    PyModule_AddIntConstant(m, "TYPE_KYMC10_16_SE", TYPE_KYMC10_16_SE);
    PyModule_AddIntConstant(m, "TYPE_CMYK11_8", TYPE_CMYK11_8);
    PyModule_AddIntConstant(m, "TYPE_CMYK11_16", TYPE_CMYK11_16);
    PyModule_AddIntConstant(m, "TYPE_CMYK11_16_SE", TYPE_CMYK11_16_SE);
    PyModule_AddIntConstant(m, "TYPE_KYMC11_8", TYPE_KYMC11_8);
    PyModule_AddIntConstant(m, "TYPE_KYMC11_16", TYPE_KYMC11_16);
    PyModule_AddIntConstant(m, "TYPE_KYMC11_16_SE", TYPE_KYMC11_16_SE);
    PyModule_AddIntConstant(m, "TYPE_CMYK12_8", TYPE_CMYK12_8);
    PyModule_AddIntConstant(m, "TYPE_CMYK12_16", TYPE_CMYK12_16);
    PyModule_AddIntConstant(m, "TYPE_CMYK12_16_SE", TYPE_CMYK12_16_SE);
    PyModule_AddIntConstant(m, "TYPE_KYMC12_8", TYPE_KYMC12_8);
    PyModule_AddIntConstant(m, "TYPE_KYMC12_16", TYPE_KYMC12_16);
    PyModule_AddIntConstant(m, "TYPE_KYMC12_16_SE", TYPE_KYMC12_16_SE);
    PyModule_AddIntConstant(m, "TYPE_XYZ_16", TYPE_XYZ_16);
    PyModule_AddIntConstant(m, "TYPE_Lab_8", TYPE_Lab_8);
    PyModule_AddIntConstant(m, "TYPE_LabV2_8", TYPE_LabV2_8);
    PyModule_AddIntConstant(m, "TYPE_ALab_8", TYPE_ALab_8);
    PyModule_AddIntConstant(m, "TYPE_ALabV2_8", TYPE_ALabV2_8);
    PyModule_AddIntConstant(m, "TYPE_Lab_16", TYPE_Lab_16);
    PyModule_AddIntConstant(m, "TYPE_LabV2_16", TYPE_LabV2_16);
    PyModule_AddIntConstant(m, "TYPE_Yxy_16", TYPE_Yxy_16);
    PyModule_AddIntConstant(m, "TYPE_YCbCr_8", TYPE_YCbCr_8);
    PyModule_AddIntConstant(m, "TYPE_YCbCr_8_PLANAR", TYPE_YCbCr_8_PLANAR);
    PyModule_AddIntConstant(m, "TYPE_YCbCr_16", TYPE_YCbCr_16);
    PyModule_AddIntConstant(m, "TYPE_YCbCr_16_PLANAR", TYPE_YCbCr_16_PLANAR);
    PyModule_AddIntConstant(m, "TYPE_YCbCr_16_SE", TYPE_YCbCr_16_SE);
    PyModule_AddIntConstant(m, "TYPE_YUV_8", TYPE_YUV_8);
    PyModule_AddIntConstant(m, "TYPE_YUV_8_PLANAR", TYPE_YUV_8_PLANAR);
    PyModule_AddIntConstant(m, "TYPE_YUV_16", TYPE_YUV_16);
    PyModule_AddIntConstant(m, "TYPE_YUV_16_PLANAR", TYPE_YUV_16_PLANAR);
    PyModule_AddIntConstant(m, "TYPE_YUV_16_SE", TYPE_YUV_16_SE);
    PyModule_AddIntConstant(m, "TYPE_HLS_8", TYPE_HLS_8);
    PyModule_AddIntConstant(m, "TYPE_HLS_8_PLANAR", TYPE_HLS_8_PLANAR);
    PyModule_AddIntConstant(m, "TYPE_HLS_16", TYPE_HLS_16);
    PyModule_AddIntConstant(m, "TYPE_HLS_16_PLANAR", TYPE_HLS_16_PLANAR);
    PyModule_AddIntConstant(m, "TYPE_HLS_16_SE", TYPE_HLS_16_SE);
    PyModule_AddIntConstant(m, "TYPE_HSV_8", TYPE_HSV_8);
    PyModule_AddIntConstant(m, "TYPE_HSV_8_PLANAR", TYPE_HSV_8_PLANAR);
    PyModule_AddIntConstant(m, "TYPE_HSV_16", TYPE_HSV_16);
    PyModule_AddIntConstant(m, "TYPE_HSV_16_PLANAR", TYPE_HSV_16_PLANAR);
    PyModule_AddIntConstant(m, "TYPE_HSV_16_SE", TYPE_HSV_16_SE);
    PyModule_AddIntConstant(m, "TYPE_NAMED_COLOR_INDEX", TYPE_NAMED_COLOR_INDEX);
    PyModule_AddIntConstant(m, "TYPE_XYZ_FLT", TYPE_XYZ_FLT);
    PyModule_AddIntConstant(m, "TYPE_XYZA_FLT", TYPE_XYZA_FLT);
    PyModule_AddIntConstant(m, "TYPE_Lab_FLT", TYPE_Lab_FLT);
    PyModule_AddIntConstant(m, "TYPE_LabA_FLT", TYPE_LabA_FLT);
    PyModule_AddIntConstant(m, "TYPE_GRAY_FLT", TYPE_GRAY_FLT);
    PyModule_AddIntConstant(m, "TYPE_RGB_FLT", TYPE_RGB_FLT);
    PyModule_AddIntConstant(m, "TYPE_RGBA_FLT", TYPE_RGBA_FLT);
    PyModule_AddIntConstant(m, "TYPE_CMYK_FLT", TYPE_CMYK_FLT);
    PyModule_AddIntConstant(m, "TYPE_XYZ_DBL", TYPE_XYZ_DBL);
    PyModule_AddIntConstant(m, "TYPE_Lab_DBL", TYPE_Lab_DBL);
    PyModule_AddIntConstant(m, "TYPE_GRAY_DBL", TYPE_GRAY_DBL);
    PyModule_AddIntConstant(m, "TYPE_RGB_DBL", TYPE_RGB_DBL);
    PyModule_AddIntConstant(m, "TYPE_CMYK_DBL", TYPE_CMYK_DBL);
    PyModule_AddIntConstant(m, "cmsERROR_UNDEFINED", cmsERROR_UNDEFINED);
    PyModule_AddIntConstant(m, "cmsERROR_FILE", cmsERROR_FILE);
    PyModule_AddIntConstant(m, "cmsERROR_RANGE", cmsERROR_RANGE);
    PyModule_AddIntConstant(m, "cmsERROR_INTERNAL", cmsERROR_INTERNAL);
    PyModule_AddIntConstant(m, "cmsERROR_NULL", cmsERROR_NULL);
    PyModule_AddIntConstant(m, "cmsERROR_READ", cmsERROR_READ);
    PyModule_AddIntConstant(m, "cmsERROR_SEEK", cmsERROR_SEEK);
    PyModule_AddIntConstant(m, "cmsERROR_WRITE", cmsERROR_WRITE);
    PyModule_AddIntConstant(m, "cmsERROR_UNKNOWN_EXTENSION", cmsERROR_UNKNOWN_EXTENSION);
    PyModule_AddIntConstant(m, "cmsERROR_COLORSPACE_CHECK", cmsERROR_COLORSPACE_CHECK);
    PyModule_AddIntConstant(m, "cmsERROR_ALREADY_DEFINED", cmsERROR_ALREADY_DEFINED);
    PyModule_AddIntConstant(m, "cmsERROR_BAD_SIGNATURE", cmsERROR_BAD_SIGNATURE);
    PyModule_AddIntConstant(m, "cmsERROR_CORRUPTION_DETECTED", cmsERROR_CORRUPTION_DETECTED);
    PyModule_AddIntConstant(m, "cmsERROR_NOT_SUITABLE", cmsERROR_NOT_SUITABLE);
    PyModule_AddIntConstant(m, "LCMS_USED_AS_INPUT", LCMS_USED_AS_INPUT);
    PyModule_AddIntConstant(m, "LCMS_USED_AS_OUTPUT", LCMS_USED_AS_OUTPUT);
    PyModule_AddIntConstant(m, "LCMS_USED_AS_PROOF", LCMS_USED_AS_PROOF);
    PyModule_AddIntConstant(m, "INTENT_PERCEPTUAL", INTENT_PERCEPTUAL);
    PyModule_AddIntConstant(m, "INTENT_RELATIVE_COLORIMETRIC", INTENT_RELATIVE_COLORIMETRIC);
    PyModule_AddIntConstant(m, "INTENT_SATURATION", INTENT_SATURATION);
    PyModule_AddIntConstant(m, "INTENT_ABSOLUTE_COLORIMETRIC", INTENT_ABSOLUTE_COLORIMETRIC);
    PyModule_AddIntConstant(m, "INTENT_PRESERVE_K_ONLY_PERCEPTUAL", INTENT_PRESERVE_K_ONLY_PERCEPTUAL);
    PyModule_AddIntConstant(m, "INTENT_PRESERVE_K_ONLY_RELATIVE_COLORIMETRIC", INTENT_PRESERVE_K_ONLY_RELATIVE_COLORIMETRIC);
    PyModule_AddIntConstant(m, "INTENT_PRESERVE_K_ONLY_SATURATION", INTENT_PRESERVE_K_ONLY_SATURATION);
    PyModule_AddIntConstant(m, "INTENT_PRESERVE_K_PLANE_PERCEPTUAL", INTENT_PRESERVE_K_PLANE_PERCEPTUAL);
    PyModule_AddIntConstant(m, "INTENT_PRESERVE_K_PLANE_RELATIVE_COLORIMETRIC", INTENT_PRESERVE_K_PLANE_RELATIVE_COLORIMETRIC);
    PyModule_AddIntConstant(m, "INTENT_PRESERVE_K_PLANE_SATURATION", INTENT_PRESERVE_K_PLANE_SATURATION);
    PyModule_AddIntConstant(m, "cmsFLAGS_NOCACHE", cmsFLAGS_NOCACHE);
    PyModule_AddIntConstant(m, "cmsFLAGS_NOOPTIMIZE", cmsFLAGS_NOOPTIMIZE);
    PyModule_AddIntConstant(m, "cmsFLAGS_NULLTRANSFORM", cmsFLAGS_NULLTRANSFORM);
    PyModule_AddIntConstant(m, "cmsFLAGS_GAMUTCHECK", cmsFLAGS_GAMUTCHECK);
    PyModule_AddIntConstant(m, "cmsFLAGS_SOFTPROOFING", cmsFLAGS_SOFTPROOFING);
    PyModule_AddIntConstant(m, "cmsFLAGS_BLACKPOINTCOMPENSATION", cmsFLAGS_BLACKPOINTCOMPENSATION);
    PyModule_AddIntConstant(m, "cmsFLAGS_NOWHITEONWHITEFIXUP", cmsFLAGS_NOWHITEONWHITEFIXUP);
    PyModule_AddIntConstant(m, "cmsFLAGS_HIGHRESPRECALC", cmsFLAGS_HIGHRESPRECALC);
    PyModule_AddIntConstant(m, "cmsFLAGS_LOWRESPRECALC", cmsFLAGS_LOWRESPRECALC);
    PyModule_AddIntConstant(m, "cmsFLAGS_8BITS_DEVICELINK", cmsFLAGS_8BITS_DEVICELINK);
    PyModule_AddIntConstant(m, "cmsFLAGS_GUESSDEVICECLASS", cmsFLAGS_GUESSDEVICECLASS);
    PyModule_AddIntConstant(m, "cmsFLAGS_KEEP_SEQUENCE", cmsFLAGS_KEEP_SEQUENCE);
    PyModule_AddIntConstant(m, "cmsFLAGS_FORCE_CLUT", cmsFLAGS_FORCE_CLUT);
    PyModule_AddIntConstant(m, "cmsFLAGS_CLUT_POST_LINEARIZATION", cmsFLAGS_CLUT_POST_LINEARIZATION);
    PyModule_AddIntConstant(m, "cmsFLAGS_CLUT_PRE_LINEARIZATION", cmsFLAGS_CLUT_PRE_LINEARIZATION);
    PyModule_AddIntConstant(m, "cmsFLAGS_NODEFAULTRESOURCEDEF", cmsFLAGS_NODEFAULTRESOURCEDEF);
}

